


// /songs/0/?albumsIds=1,2,3,4,5&playlistsId=1,2,3,4,5
// ALMOST FULL CLIENT SIDE
// A PROVIDER TO STORE SELECTED SONGS XXXXXXXXXXXXXXXXXXXXXX
// STORE THE SONGS ON BACKEND DIRECT IN GAME CLASS
// SHOW UNPLAYABLE SONGS
// ENSURE USER SELECTED AT LEAST 3 SONGS
// INDEX WILL BE SEQUENTIAL, ALBUMS -> PLAYLISTS